name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todo dia à meia-noite UTC
  workflow_dispatch:     # Também permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: davidsants04  
          outputs: dist/snake.svg
          color: '#000000'                # Cor da cobrinha preta
          # background não tem suporte oficial ainda, o fundo ficará transparente

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
